In [ ]:
import pandas as pd
df=pd.read_csv('/content/customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
labels=['Young Adult','Adult','middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)
df[['age','age_group']].head(10)

   age    age_group
0   55  middle-aged
1   19  Young Adult
2   50  middle-aged
3   21  Young Adult
4   45  middle-aged
5   46  middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  middle-aged

In [ ]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [ ]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [ ]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [ ]:
df=df.drop(columns=['promo_code_used'])
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [ ]:
import sqlite3
conn=sqlite3.connect("my_database.db")
print("Database created successfully!")

Database created successfully!

In [ ]:
pip install psycopg2-binary scikit_learn SQLAlchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.13/dist-packages (2.9.13)
Requirement already satisfied: scikit_learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.13/dist-packages (2.1.5)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (3.7.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from SQLAlchemy) (4.16.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit_learn) (3.1.2)

In [ ]:
import pandas as pd
import psycopg2
import sklearn
from sqlalchemy import create_engine
print("All libraries imported successfully!")

All libraries imported successfully!

In [ ]:
df.to_sql(
    name="customer_shopping_behavior",
    con=conn,
    if_exists="replace",
    index=False
)

3900

In [ ]:
import pandas as pd
query="SELECT * FROM customer_shopping_behavior"
df=pd.read_sql(query,conn)
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle-aged,365

In [ ]:
pip install psycopg2-binary sqlalchemy scikit_learn

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.13/dist-packages (2.9.13)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.1.5)
Requirement already satisfied: scikit_learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit_learn) (3.1.2)

In [ ]:
%pip install -q psycopg2-binary sqlalchemy

In [ ]:
from getpass import getpass
from sqlalchemy import create_engine, text

raw_url = getpass("//neondb_owner:npg_inR5KbD1FMuj@ep-sparkling-frog-b4q2cst6-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require")

# Ensure we explicitly use the psycopg2 driver instead of the default psycopg3 (psycopg)
if raw_url.startswith("postgresql://"):
    DATABASE_URL = raw_url.replace("postgresql://", "postgresql+psycopg2://", 1)
elif not raw_url.startswith("postgresql+psycopg2://") and raw_url.startswith("//"):
    DATABASE_URL = "postgresql+psycopg2:" + raw_url
else:
    DATABASE_URL = raw_url

engine = create_engine(DATABASE_URL)

with engine.connect() as conn:
    result = conn.execute(text("SELECT version()"))
    print(result.scalar())

//neondb_owner:npg_inR5KbD1FMuj@ep-sparkling-frog-b4q2cst6-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require··········
PostgreSQL 18.6 (fd34222) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit

In [ ]:
with engine.begin() as connection:
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS connection_test (
            id SERIAL PRIMARY KEY,
            message TEXT
        )
    """))

    connection.execute(
        text("""
            INSERT INTO connection_test (message)
            VALUES (:message)
        """),
        {"message": "Connected from Google Colab!"}
    )

with engine.connect() as connection:
    result = connection.execute(
        text("SELECT * FROM connection_test")
    )

    for row in result:
        print(row)

(1, 'Connected from Google Colab!')
(2, 'Connected from Google Colab!')
(3, 'Connected from Google Colab!')
(4, 'Connected from Google Colab!')

In [ ]:
from sqlalchemy import text
import pandas as pd

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT current_database(), current_schema();
    """))
    print("Database and schema:", result.fetchone())

    tables = connection.execute(text("""
        SELECT table_schema, table_name
        FROM information_schema.tables
        WHERE table_schema = 'public';
    """))

    print("Tables in PostgreSQL:")
    for row in tables:
        print(row)

Database and schema: ('neondb', 'public')
Tables in PostgreSQL:
('public', 'connection_test')
('public', 'customer_shopping_behavior')

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'my_database.db', 'customer_shopping_behavior.csv', 'sample_data']

In [ ]:
import pandas as pd

df = pd.read_csv("/content/customer_shopping_behavior.csv")

print(df.shape)
display(df.head())

(3900, 18)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
engine.dispose()

print("Database connections reset!")

Database connections reset!

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(DATABASE_URL)

with engine.connect() as connection:
    print(connection.execute(text("SELECT 1")).scalar())

1

In [ ]:
df.to_sql(
    name="customer_shopping_behavior",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False
)

print("Dataset uploaded successfully!")

Dataset uploaded successfully!

In [ ]:
with engine.connect() as connection:
    count = connection.execute(
        text("SELECT COUNT(*) FROM public.customer_shopping_behavior")
    ).scalar()

    print("Rows in PostgreSQL:", count)

Rows in PostgreSQL: 3900

In [ ]:
query = """
SELECT
    "Gender",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM public.customer_shopping_behavior
GROUP BY "Gender";
"""

result = pd.read_sql_query(query, engine)
display(result)

   Gender  total_revenue
0  Female        75191.0
1    Male       157890.0

In [ ]:
query = """
SELECT *
FROM public.customer_shopping_behavior
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" > (
      SELECT AVG("Purchase Amount (USD)")
      FROM public.customer_shopping_behavior
  );
"""

result = pd.read_sql_query(query, engine)
display(result)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
1,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
2,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
3,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
4,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,1667,51,Male,Skirt,Clothing,64,Arkansas,M,Blue,Summer,3.1,No,Store Pickup,Yes,Yes,47,PayPal,Annually
835,1671,22,Male,Pants,Clothing,73,Utah,L,Cyan,Fall,3.6,No,Free Shipping,Yes,Yes,20,Cash,Weekly
836,1673,18,Male,Boots,Footwear,73,South Carolina,L,Gold,Fall,3.8,No,Free Shipping,Yes,Yes,15,Venmo,Quarterly
837,1674,21,Male,Blouse,Clothing,62,Hawaii,M,Violet,Fall,3.4,No,Next Day Air,Yes,Yes,49,Venmo,Bi-Weekly
838,1676,35,Male,Pants,Clothing,90,Colorado,M,Beige,Spring,4.7,No,Next Day Air,Yes,Yes,21,Credit Card,Annually

In [ ]:
query = """
SELECT
    "Item Purchased",
    AVG("Review Rating") AS average_rating
FROM public.customer_shopping_behavior
GROUP BY "Item Purchased"
ORDER BY average_rating DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Item Purchased  average_rating
0         Gloves        3.862774
1        Sandals        3.844654
2          Boots        3.818881
3            Hat        3.801307
4          Skirt        3.785350

In [ ]:
engine.dispose()

with engine.connect() as connection:
    print(connection.exec_driver_sql("SELECT 1").scalar())

1

In [ ]:

query = """
SELECT
    COUNT(*) AS total_customers,
    ROUND(AVG("Purchase Amount (USD)"), 2) AS average_purchase
FROM public.customer_shopping_behavior
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" > (
      SELECT AVG("Purchase Amount (USD)")
      FROM public.customer_shopping_behavior
  );
"""

result = pd.read_sql_query(query, engine)
display(result)

   total_customers  average_purchase
0              839             79.79

In [ ]:
query = """
SELECT
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS average_spending
FROM public.customer_shopping_behavior
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type"
ORDER BY average_spending DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Shipping Type  average_spending
0       Express         60.475232
1      Standard         58.460245

In [ ]:
query = """
SELECT
    "Subscription Status",
    AVG("Purchase Amount (USD)") AS average_spending,
    COUNT(*) AS total_customers
FROM public.customer_shopping_behavior
GROUP BY "Subscription Status"
ORDER BY average_spending DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Subscription Status  average_spending  total_customers
0                  No         59.865121             2847
1                 Yes         59.491928             1053

In [ ]:
query = """
SELECT
    "Item Purchased",
    COUNT(*) AS total_purchases,
    SUM(
        CASE
            WHEN "Discount Applied" = 'Yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN "Discount Applied" = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM public.customer_shopping_behavior
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Item Purchased  total_purchases  discounted_purchases  discount_percentage
0            Hat              154                    77                50.00
1       Sneakers              145                    72                49.66
2           Coat              161                    79                49.07
3        Sweater              164                    79                48.17
4          Pants              171                    81                47.37

In [ ]:
query = """
SELECT
    "Previous Purchases",
    COUNT(*) AS total_customers
FROM public.customer_shopping_behavior
GROUP BY "Previous Purchases"
ORDER BY "Previous Purchases";
"""

result = pd.read_sql_query(query, engine)
display(result)

    Previous Purchases  total_customers
0                    1               83
1                    2               72
2                    3               91
3                    4               91
4                    5               87
5                    6               87
6                    7               65
7                    8               67
8                    9               65
9                   10               76
10                  11               82
11                  12               79
12                  13               69
13                  14               92
14                  15               73
15                  16               70
16                  17               67
17                  18               84
18                  19               78
19                  20               83
20                  21               96
21                  22               65
22                  23               73
23                  24               91
24                  25               79
25                  26               77
26                  27               78
27                  28               80
28                  29               69
29                  30               82
30                  31               97
31                  32               81
32                  33               82
33                  34               79
34                  35               63
35                  36               71
36                  37               78
37                  38               70
38                  39               81
39                  40               82
40                  41               70
41                  42               83
42                  43               64
43                  44               72
44                  45               83
45                  46               78
46                  47               90
47                  48               90
48                  49               58
49                  50               77

In [ ]:
query = """
WITH product_counts AS (
    SELECT
        "Category",
        "Item Purchased",
        COUNT(*) AS total_purchases
    FROM public.customer_shopping_behavior
    GROUP BY "Category", "Item Purchased"
),
ranked_products AS (
    SELECT
        "Category",
        "Item Purchased",
        total_purchases,
        DENSE_RANK() OVER (
            PARTITION BY "Category"
            ORDER BY total_purchases DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    "Category",
    "Item Purchased",
    total_purchases,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY "Category", product_rank;
"""

result = pd.read_sql_query(query, engine)
display(result)

       Category Item Purchased  total_purchases  product_rank
0   Accessories        Jewelry              171             1
1   Accessories     Sunglasses              161             2
2   Accessories           Belt              161             2
3   Accessories          Scarf              157             3
4      Clothing          Pants              171             1
5      Clothing         Blouse              171             1
6      Clothing          Shirt              169             2
7      Clothing          Dress              166             3
8      Footwear        Sandals              160             1
9      Footwear          Shoes              150             2
10     Footwear       Sneakers              145             3
11    Outerwear         Jacket              163             1
12    Outerwear           Coat              161             2

In [ ]:
query = """
SELECT
    "Subscription Status",
    CASE
        WHEN "Previous Purchases" = 1 THEN 'First-time repeat'
        WHEN "Previous Purchases" > 1 THEN 'Repeat buyer'
        ELSE 'No previous purchases'
    END AS buyer_type,
    COUNT(*) AS total_records
FROM public.customer_shopping_behavior
GROUP BY
    "Subscription Status",
    buyer_type
ORDER BY buyer_type, "Subscription Status";
"""

result = pd.read_sql_query(query, engine)
display(result)

  Subscription Status         buyer_type  total_records
0                  No  First-time repeat             68
1                 Yes  First-time repeat             15
2                  No       Repeat buyer           2779
3                 Yes       Repeat buyer           1038

In [ ]:
query = """
SELECT
    CASE
        WHEN "Age" < 25 THEN 'Under 25'
        WHEN "Age" BETWEEN 25 AND 34 THEN '25-34'
        WHEN "Age" BETWEEN 35 AND 44 THEN '35-44'
        WHEN "Age" BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55 and above'
    END AS age_group,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM public.customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

      age_group  total_revenue
0  55 and above        69590.0
1         25-34        45400.0
2         45-54        45370.0
3         35-44        43463.0
4      Under 25        29258.0

In [ ]:

query = """
SELECT
    "Item Purchased",
    ROUND(AVG("Review Rating")::numeric, 2) AS average_rating
FROM public.customer_shopping_behavior
GROUP BY "Item Purchased"
ORDER BY average_rating DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Item Purchased  average_rating
0         Gloves            3.86
1        Sandals            3.84
2          Boots            3.82
3            Hat            3.80
4          Skirt            3.79

In [ ]:

query = """
SELECT
    "Shipping Type",
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase,
    COUNT(*) AS total_orders
FROM public.customer_shopping_behavior
GROUP BY "Shipping Type"
ORDER BY average_purchase DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

    Shipping Type  average_purchase  total_orders
0  2-Day Shipping             60.73           627
1         Express             60.48           646
2   Free Shipping             60.41           675
3    Store Pickup             59.89           650
4    Next Day Air             58.63           648
5        Standard             58.46           654

In [ ]:

query = """
SELECT
    "Subscription Status",
    COUNT(*) AS total_customers,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_spending
FROM public.customer_shopping_behavior
GROUP BY "Subscription Status"
ORDER BY average_spending DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Subscription Status  total_customers  average_spending
0                  No             2847             59.87
1                 Yes             1053             59.49

In [ ]:

query = """
SELECT
    "Item Purchased",
    COUNT(*) AS total_purchases,
    SUM(CASE
        WHEN "Discount Applied" = 'Yes' THEN 1
        ELSE 0
    END) AS discounted_purchases,
    ROUND(
        100.0 * SUM(CASE
            WHEN "Discount Applied" = 'Yes' THEN 1
            ELSE 0
        END) / COUNT(*),
        2
    ) AS discount_percentage
FROM public.customer_shopping_behavior
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Item Purchased  total_purchases  discounted_purchases  discount_percentage
0            Hat              154                    77                50.00
1       Sneakers              145                    72                49.66
2           Coat              161                    79                49.07
3        Sweater              164                    79                48.17
4          Pants              171                    81                47.37

In [ ]:

query = """
SELECT
    CASE
        WHEN "Age" < 20 THEN 'Under 20'
        WHEN "Age" BETWEEN 20 AND 29 THEN '20-29'
        WHEN "Age" BETWEEN 30 AND 39 THEN '30-39'
        WHEN "Age" BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS age_group,
    COUNT(*) AS total_purchases,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY age_group
ORDER BY age_group;
"""

result = pd.read_sql_query(query, engine)
display(result)

  age_group  total_purchases  average_purchase
0     20-29              728             60.20
1     30-39              724             60.14
2     40-49              739             58.49
3       50+             1559             59.92
4  Under 20              150             60.53

In [ ]:

query = """
WITH product_counts AS (
    SELECT
        "Category",
        "Item Purchased",
        COUNT(*) AS purchase_count,
        DENSE_RANK() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM public.customer_shopping_behavior
    GROUP BY "Category", "Item Purchased"
)
SELECT
    "Category",
    "Item Purchased",
    purchase_count,
    product_rank
FROM product_counts
WHERE product_rank <= 3
ORDER BY "Category", product_rank;
"""

result = pd.read_sql_query(query, engine)
display(result)

       Category Item Purchased  purchase_count  product_rank
0   Accessories        Jewelry             171             1
1   Accessories     Sunglasses             161             2
2   Accessories           Belt             161             2
3   Accessories          Scarf             157             3
4      Clothing          Pants             171             1
5      Clothing         Blouse             171             1
6      Clothing          Shirt             169             2
7      Clothing          Dress             166             3
8      Footwear        Sandals             160             1
9      Footwear          Shoes             150             2
10     Footwear       Sneakers             145             3
11    Outerwear         Jacket             163             1
12    Outerwear           Coat             161             2

In [ ]:

query = """
SELECT
    CASE
        WHEN "Age" < 20 THEN 'Under 20'
        WHEN "Age" BETWEEN 20 AND 29 THEN '20-29'
        WHEN "Age" BETWEEN 30 AND 39 THEN '30-39'
        WHEN "Age" BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS age_group,
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM public.customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

query = """
SELECT
    "Payment Method",
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Payment Method"
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

  age_group  total_purchases  total_revenue
0       50+             1559        93410.0
1     20-29              728        43825.0
2     30-39              724        43541.0
3     40-49              739        43225.0
4  Under 20              150         9080.0

  Payment Method  total_purchases  total_revenue  average_purchase
0    Credit Card              671        40310.0             60.07
1         PayPal              677        40109.0             59.25
2           Cash              670        40002.0             59.70
3     Debit Card              636        38742.0             60.92
4          Venmo              634        37374.0             58.95
5  Bank Transfer              612        36544.0             59.71

In [ ]:

query = """
SELECT
    CASE
        WHEN "Previous Purchases" BETWEEN 1 AND 5 THEN '1-5 Purchases'
        WHEN "Previous Purchases" BETWEEN 6 AND 10 THEN '6-10 Purchases'
        WHEN "Previous Purchases" BETWEEN 11 AND 20 THEN '11-20 Purchases'
        ELSE '21+ Purchases'
    END AS purchase_frequency_group,
    COUNT(*) AS customer_records,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY purchase_frequency_group
ORDER BY MIN("Previous Purchases");
"""

result = pd.read_sql_query(query, engine)
display(result)

  purchase_frequency_group  customer_records  average_purchase
0            1-5 Purchases               424             60.59
1           6-10 Purchases               360             60.76
2          11-20 Purchases               777             59.05
3            21+ Purchases              2339             59.70

In [ ]:

query = """
SELECT
    "Shipping Type",
    COUNT(*) AS total_orders,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Shipping Type"
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

    Shipping Type  total_orders  total_revenue  average_purchase
0   Free Shipping           675        40777.0             60.41
1         Express           646        39067.0             60.48
2    Store Pickup           650        38931.0             59.89
3        Standard           654        38233.0             58.46
4  2-Day Shipping           627        38080.0             60.73
5    Next Day Air           648        37993.0             58.63

In [ ]:

query = """
SELECT
    "Category",
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Category"
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

      Category  total_purchases  total_revenue  average_purchase
0     Clothing             1737       104264.0             60.03
1  Accessories             1240        74200.0             59.84
2     Footwear              599        36093.0             60.26
3    Outerwear              324        18524.0             57.17

In [ ]:

query = """
SELECT
    "Category",
    COUNT("Review Rating") AS total_reviews,
    ROUND(AVG("Review Rating")::numeric, 2) AS average_rating,
    MIN("Review Rating") AS lowest_rating,
    MAX("Review Rating") AS highest_rating
FROM public.customer_shopping_behavior
GROUP BY "Category"
ORDER BY average_rating DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

      Category  total_reviews  average_rating  lowest_rating  highest_rating
0     Footwear            594            3.79            2.5             5.0
1  Accessories           1229            3.77            2.5             5.0
2    Outerwear            322            3.75            2.5             5.0
3     Clothing           1718            3.72            2.5             5.0

In [ ]:

query = """
SELECT
    "Gender",
    COUNT(*) AS total_purchases,
    SUM(
        CASE
            WHEN "Discount Applied" = 'Yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN "Discount Applied" = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM public.customer_shopping_behavior
GROUP BY "Gender"
ORDER BY discount_percentage DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

   Gender  total_purchases  discounted_purchases  discount_percentage
0    Male             2652                  1677                63.24
1  Female             1248                     0                 0.00

In [ ]:

query = """
SELECT
    "Gender",
    "Category",
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Gender", "Category"
ORDER BY "Gender", total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

   Gender     Category  total_purchases  total_revenue  average_purchase
0  Female     Clothing              556        33636.0             60.50
1  Female  Accessories              392        23819.0             60.76
2  Female     Footwear              199        11835.0             59.47
3  Female    Outerwear              101         5901.0             58.43
4    Male     Clothing             1181        70628.0             59.80
5    Male  Accessories              848        50381.0             59.41
6    Male     Footwear              400        24258.0             60.65
7    Male    Outerwear              223        12623.0             56.61

In [ ]:

query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT("Customer ID") AS non_missing_customer_ids,
    COUNT("Purchase Amount (USD)") AS non_missing_purchase_amounts,
    COUNT("Review Rating") AS non_missing_review_ratings
FROM public.customer_shopping_behavior;
"""

result = pd.read_sql_query(query, engine)
display(result)

,total_rows,non_missing_customer_ids,non_missing_purchase_amounts,non_missing_review_ratings
0,3900,3900,3900,3863

In [ ]:

query = """
SELECT
    COUNT(*) AS total_records,
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase,
    ROUND(AVG("Review Rating")::numeric, 2) AS average_rating,
    COUNT(DISTINCT "Customer ID") AS unique_customers
FROM public.customer_shopping_behavior;
"""

result = pd.read_sql_query(query, engine)
display(result)

,total_records,total_revenue,average_purchase,average_rating,unique_customers
0,3900,233081.0,59.76,3.75,3900

In [ ]:
query = """
SELECT
    COUNT(*) AS total_records,
    SUM("Purchase Amount (USD)") AS total_revenue,
    AVG("Purchase Amount (USD)") AS average_purchase,
    AVG("Review Rating") AS average_rating,
    COUNT(DISTINCT "Customer ID") AS distinct_customers
FROM public.customer_shopping_behavior;
"""

result = pd.read_sql_query(query, engine)
display(result)

,total_records,total_revenue,average_purchase,average_rating,distinct_customers
0,3900,233081.0,59.764359,3.750065,3900

In [ ]:
query = """
SELECT
    "Category",
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Category"
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

      Category  total_purchases  total_revenue  average_purchase
0     Clothing             1737       104264.0             60.03
1  Accessories             1240        74200.0             59.84
2     Footwear              599        36093.0             60.26
3    Outerwear              324        18524.0             57.17

In [ ]:
query = """
SELECT
    "Discount Applied",
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Discount Applied"
ORDER BY total_purchases DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

  Discount Applied  total_purchases  total_revenue  average_purchase
0               No             2223       133670.0             60.13
1              Yes             1677        99411.0             59.28

In [ ]:
query = """
SELECT
    "Shipping Type",
    COUNT(*) AS total_purchases,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS average_purchase
FROM public.customer_shopping_behavior
GROUP BY "Shipping Type"
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, engine)
display(result)

    Shipping Type  total_purchases  total_revenue  average_purchase
0   Free Shipping              675        40777.0             60.41
1         Express              646        39067.0             60.48
2    Store Pickup              650        38931.0             59.89
3        Standard              654        38233.0             58.46
4  2-Day Shipping              627        38080.0             60.73
5    Next Day Air              648        37993.0             58.63